site_name: My Docs
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Architecture Diagrams: architecture-diagrams.md

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js