site_name: My Docs

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Extension Test: full-extension-demo.md
  - Architecture Diagrams: architecture-diagrams.md

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js